#!/usr/bin/env bash
#This script starts the nginx service, waits for a second to make sure it's up and running, then uses curl to check if the nginx server is accessible on port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
