#!/usr/bin/env bash
#This script starts the nginx service, waits for a second to make sure it's up and running, then uses curl to check if the nginx server is accessible on port 80.
sudo apt-get update
sudo apt-get install nginx -y
sudo systemctl stop nginx
sudo sed -i 's/80/8080/g' /etc/nginx/nginx.conf
sudo systemctl start nginx
